/**
 * @fileoverview Tags for categorizing GDE activities
 * @description Enum defining all available tags for categorizing Google Developer Expert activities
 */

/**
 * Enum for activity tags
 * Used to categorize activities across different Google technologies and initiatives
 * Contains 108 different tag values for GDE activities
 */
export enum Tag {
  AI = "AI",
  AI_AI_STUDIO = "AI - AI Studio",
  AI_AGENT_DEVELOPMENT_KIT = "AI - Agent Development Kit (ADK)",
  AI_AGENTS = "AI - Agents",
  AI_COLAB = "AI - Colab",
  AI_GEMINI = "AI - Gemini",
  AI_GEMMA = "AI - Gemma",
  AI_GENERATIVE_AI = "AI - Generative AI",
  AI_JAX = "AI - JAX",
  AI_KAGGLE = "AI - Kaggle",
  AI_KERAS = "AI - Keras",
  AI_LLM = "AI - LLM",
  AI_LITERT = "AI - LiteRT",
  AI_ML_ENGINEERING = "AI - ML Engineering (MLOps)",
  AI_MEDIAPIPE = "AI - MediaPipe",
  AI_ON_DEVICE_AI = "AI - On-Device AI",
  AI_RESPONSIBLE_AI = "AI - Responsible AI",
  AI_TPU = "AI - TPU",
  AI_TENSORFLOW = "AI - TensorFlow",
  AI_VERTEX_AI = "AI - Vertex AI",
  AI_MATH_CLUBS = "AI Math Clubs",
  AI_PAPER_READING_CLUBS = "AI Paper Reading Clubs",
  AR_VR = "AR/VR",
  ANDROID = "Android",
  ANDROID_ARCORE = "Android - ARCore",
  ANDROID_AUTO = "Android - Android Auto",
  ANDROID_DEV_TOOLS = "Android - Android Dev Tools",
  ANDROID_STUDIO = "Android - Android Studio",
  ANDROID_TV = "Android - Android TV",
  ANDROID_APP_ARCHITECTURE = "Android - App Architecture & Arch Components",
  ANDROID_APP_INDEXING = "Android - App Indexing",
  ANDROID_APP_PERFORMANCE = "Android - App Performance",
  ANDROID_APP_QUALITY = "Android - App Quality",
  ANDROID_CAMERA = "Android - Camera",
  ANDROID_COMPOSER = "Android - Composer",
  ANDROID_FORM_FACTORS = "Android - Form Factors",
  ANDROID_GEMINI_NANO = "Android - Gemini Nano",
  ANDROID_JETPACK = "Android - Jetpack",
  ANDROID_JETPACK_COMPOSE = "Android - Jetpack Compose",
  ANDROID_KOTLIN = "Android - Kotlin",
  ANDROID_MATERIAL_DESIGN = "Android - Material Design",
  ANDROID_MEDIA = "Android - Media",
  ANDROID_MODERN_ANDROID_DEVELOPMENT = "Android - Modern Android Development",
  ANDROID_MODERN_UI = "Android - Modern UI",
  ANDROID_NDK = "Android - NDK",
  ANDROID_PASSKEYS = "Android - Passkeys",
  ANDROID_PERFORMANCE = "Android - Performance",
  ANDROID_VULKAN = "Android - Vulkan",
  ANDROID_WEAR_OS = "Android - Wear OS",
  ANDROID_WIDGETS = "Android - Widgets",
  ANDROID_XR = "Android - XR",
  ANGULAR = "Angular",
  BUILD_WITH_AI = "Build with AI",
  CLOUD_AI_TOOLS = "Cloud - AI Tools",
  CLOUD_API_GATEWAYS = "Cloud - API Gateways",
  CLOUD_APP_DEVELOPMENT = "Cloud - App Development",
  CLOUD_COMPUTE_NETWORKING_STORAGE = "Cloud - Compute, Networking, Storage",
  CLOUD_DATA = "Cloud - Data",
  CLOUD_OPERATIONS_MANAGEMENT = "Cloud - Operations & Management",
  CLOUD_SECURITY = "Cloud - Security",
  CLOUD_SERVERLESS_CONTAINERS = "Cloud - Serverless & Containers",
  CLOUD_STUDY_JAM = "Cloud Study Jam",
  DART = "Dart",
  DEVFEST = "DevFest",
  DIVERSITY_INCLUSION = "Diversity & Inclusion",
  EARTH_ENGINE = "Earth Engine",
  FIREBASE = "Firebase",
  FIREBASE_AB_TESTING = "Firebase - A/B Testing",
  FIREBASE_AI_MONITORING = "Firebase - AI Monitoring",
  FIREBASE_ANALYTICS = "Firebase - Analytics",
  FIREBASE_APP_HOSTING = "Firebase - App Hosting",
  FIREBASE_AUTHENTICATION = "Firebase - Authentication",
  FIREBASE_CLOUD_MESSAGING = "Firebase - Cloud Messaging",
  FIREBASE_DATA_CONNECT = "Firebase - Data Connect",
  FIREBASE_FIREBASE_STUDIO = "Firebase - Firebase Studio",
  FIREBASE_FIRESTORE = "Firebase - Firestore",
  FIREBASE_GENKIT = "Firebase - Genkit",
  FIREBASE_PERFORMANCE = "Firebase - Performance",
  FIREBASE_REALTIME_DATABASE = "Firebase - Realtime Database",
  FIREBASE_REMOTE_CONFIG = "Firebase - Remote Config",
  FIREBASE_TEST_LAB = "Firebase - Test Lab",
  FIREBASE_VERTEX_AI = "Firebase - Vertex AI in Firebase",
  FLUTTER = "Flutter",
  GOLANG = "Golang",
  GOOGLE_CLOUD = "Google Cloud",
  GOOGLE_IO_EXTENDED = "Google I/O Extended",
  GOOGLE_MAPS_PLATFORM = "Google Maps Platform",
  GOOGLE_WORKSPACE = "Google Workspace",
  INTERNATIONAL_WOMENS_DAY = "International Women's Day",
  ML_STUDY_JAMS = "ML Study Jams",
  OPEN_SOURCE = "Open Source",
  PAYMENTS = "Payments",
  PAYMENTS_GOOGLE_PAY = "Payments - Google Pay",
  PAYMENTS_GOOGLE_WALLET = "Payments - Google Wallet",
  ROAD_TO_GOOGLE_DEVELOPERS_CERTIFICATION = "Road to Google Developers Certification",
  UX_UI_DESIGN = "UX / UI Design",
  WEB = "Web",
  WEB_AI_FOR_WEB_DEVELOPERS = "Web - AI for Web Developers",
  WEB_BROWSER_EXTENSIONS = "Web - Browser Extensions",
  WEB_CSS_UI = "Web - CSS & UI",
  WEB_DEVTOOLS_BROWSER_AUTOMATION = "Web - DevTools & Browser Automation",
  WEB_FUGU_PWA_APIS = "Web - Fugu/PWA APIs",
  WEB_IDENTITY = "Web - Identity",
  WEB_PERFORMANCE = "Web - Performance",
  WORKSPACE_ADD_ONS = "Workspace - Add Ons",
  WORKSPACE_APPSHEET = "Workspace - AppSheet",
  WORKSPACE_GOOGLE_APPS_SCRIPT = "Workspace - Google Apps Script",
  WORKSPACE_GOOGLE_WORKSPACE_REST_APIS = "Workspace - Google Workspace (REST) APIs",
}
